# Generated by Django 5.2 on 2025-05-07 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Loro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('tamaño', models.CharField(max_length=100)),
                ('edad', models.IntegerField()),
                ('color', models.CharField(max_length=50)),
            ],
        ),
    ]
